version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  k6:
    image: grafana/k6
    container_name: k6
    stdin_open: true
    tty: true
    working_dir: /scripts
    volumes:
      - ./coupon-issue:/scripts


volumes:
  influxdb-data:
  grafana-data: